### ISSUE TITLE
Support multiple providers/configurations

### ISSUE THREAD

**Issue by timuralp** [gaul/s3proxy#11]
It would be great to be able to support multiple providers/configurations through a single S3Proxy process. For example, by specifying AWS S3 and GCS, one could transfer data from one provider to another (there are a bunch of other use cases).

One way to do this would be to use the location (but that feels like an incorrect patch, as the location itself may be useful to express).

Another way would be through an extended endpoint path, e.g. http://127.0.0.1/aws and http://127.0.0.1/gcs.

**Comment by andrewgaul** [comment]
We could support multiple `--properties` flags, although this is not much different from users invoking multiple S3Proxy process.

**Comment by gaul** [comment]
Muxing off of the access key ID seems like the most reasonable thing to do.  Using the port requires listening on more sockets and path gets overloaded with service paths.
