### ISSUE TITLE
Java 8 dependency

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#121]
S3Proxy requires Java 7 presently.  Requiring Java 8 would allow upgrading some dependencies:

- Checkstyle 7.0 http://checkstyle.sourceforge.net/releasenotes.html#Release_7.0
- error-prone 2.0.6 https://groups.google.com/forum/#!topic/error-prone-announce/ycJBeaNK3Uc
- Jetty 9.3 https://webtide.com/jetty-9-3-features/

These do not seem compelling and older distributions like Ubuntu 14.04 LTS do not provide Java 8.  Keeping this bug open for tracking.

**Comment by rbjorklin** [comment]
A Java 8 PPA can be found here though: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

**Comment by andrewgaul** [comment]
Moving to JDK 8 would enable using Nashorn for JavaScript middlewares discussed in #181.

@shenghu @SpandanThakur You both spoke about the JDK 8 dependency in #190.  Any opposition to moving now?

**Comment by SpandanThakur** [comment]
@andrewgaul No opposition. I think moving to JDK 8 would be a good move.

**Comment by gaul** [comment]
jclouds 2.2.0 will require Java 8 so S3Proxy will move forward with it.

**Comment by gaul** [comment]
S3Proxy 1.8.0 requires Java 8 so we can upgrade these dependencies now.
