### ISSUE TITLE
BucketAlreadyOwnedByYou error on new install

### ISSUE THREAD

**Issue by stephzylstra** [gaul/s3proxy#122]
Hi, I'm having issues getting beyond the readme in order to get it running.

s3proxy 1.4.0, commit `bb68ff5`

The only change to the default config in the readme is that I'm using port 9090 instead of 8080; i.e. my s3proxy.conf file is:

``` s3proxy.authorization=none
s3proxy.endpoint=http://127.0.0.1:9090
jclouds.provider=filesystem
jclouds.identity=identity
jclouds.credential=credential
jclouds.filesystem.basedir=/tmp/s3proxy
```

When running:

```
$ curl --request PUT http://localhost:9090/test
<?xml version="1.0" ?><Error><Code>BucketAlreadyOwnedByYou</Code><Message></Message><BucketName>test</BucketName><RequestId>4442587FB7D0A2F9</RequestId></Error>
```

Still looking into it but any help would be appreciated.

Thanks!

**Comment by kahing** [comment]
Is there already a test directory?

**Comment by stephzylstra** [comment]
No. The file path in the configuration is empty.

**Comment by stephzylstra** [comment]
The issue appears to be a permissions issue, presumably due to using a subdirectory of /tmp.

When I run s3proxy using `./target/s3proxy --properties s3proxy.conf`, the error appears. When I run it with the same configuration file using `sudo ./target/s3proxy --properties s3proxy.conf`, the bucket is created normally.

Is it worth rewriting the error message here so that it's more helpful?

**Comment by gaul** [comment]
@stephzylstra I committed fixes to jclouds and S3Proxy which will propagate `AccessDenied` in this situation.  Unfortunately we must wait for the former to release 2.1.0 before we can close this issue.
