### ISSUE TITLE
using google-cloud-storage for provider is significantly slower than s3

### ISSUE THREAD

**Issue by chicagobuss** [gaul/s3proxy#129]
For whatever reason, uploads using the native `google-cloud-storage` provider (and boto as the client) seem to be taking WAY longer than the `s3` provider (s3 provider but still actually using GCS). Not sure why this is but thought I should note it. Downloads are pretty much just as fast.

Using GCS with the `s3` provider:

```
(env)[cb@test-upload tests]$ time ./upload-local-s3-proxy.py out.csv
Uploading out-180.csv to bucket dabucket
..........
real    0m7.776s
user    0m0.771s
sys     0m0.335s
(env)[cb@test-upload tests]$ time ./download-local-s3-proxy.py out.csv
Downloading out-180.csv from bucket dabucket
..........
real    0m7.512s
user    0m0.981s
sys     0m0.569s
```

After switching s3proxy to use the `google-cloud-storage` provider:

```
(env)[cb@test-upload tests]$ time ./upload-local-s3-proxy.py out.csv
Uploading out-180.csv to bucket dabucket
..........
real    0m45.132s
user    0m0.762s
sys     0m0.316s
(env)[cb@test-upload tests]$ time ./download-local-s3-proxy.py out.csv
Downloading out-180.csv from bucket dabucket
..........
real    0m8.092s
user    0m1.009s
sys     0m0.618s
```

**Comment by andrewgaul** [comment]
I suspect that different regions are being tested between AWS and GCS.  Would be good to verify the created container.

**Comment by gaul** [comment]
GCS and S3 providers have the same performance in my testing.  Please reopen if you can reproduce these symptoms.
