### ISSUE TITLE
Implement list objects v2

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#168]
Breaks `marker` into `continuation-token` and `start-after` and adds `fetch-owner` option.  Reference:

https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

**Comment by Pluto1010** [comment]
I would also be happy to this feature. I'm trying to enable my QNAP NAS to backup my data to B2 instead of Microsoft's Azure through s3proxy. I've tried accessing the storage through s3proxy using Cyberduck and learned that listing is not supported yet.

Can I help to do this?

**Comment by andrewgaul** [comment]
@Pluto1010 Strange that Cyberduck does not fallback to list objects v1 when v2 emit `NotImplemented`; you should also follow up with its authors.  I believe adding support for v2 is straightforward; S3Proxy has a limited notion of owner so simply fake that but you need to investigate the difference between `marker` and `star-after`.  My intuition is that you just replace one with the other but this may have more subtlety.

**Comment by jumenzel** [comment]
It would be great to add list objects v2 support to s3proxy. It appears though that jclouds does not support the `continuation-token` or know how to call s3 using the list-type=2 query param. So even if s3proxy supported list objects v2 how wouldn't really help. But I'm also new to this so maybe I've drawn the wrong conclusion. Any ideas?

**Comment by gaul** [comment]
Sorry for my tardy response; I was traveling for several weeks.  It looks like you implemented this in vyasa-analytics/s3proxy#1; could you submit a pull request here?
