### ISSUE TITLE
Shade jclouds (due to Guava)

### ISSUE THREAD

**Issue by ben-manes** [gaul/s3proxy#209]
JClouds is stuck on an old version of Guava (16) which is incompatible with the latest version. That project hasn't settled on a compatibility strategy and [recommends](https://issues.apache.org/jira/browse/JCLOUDS-1225?focusedCommentId=15950333&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15950333) that consumers shade it instead.

I'd like to use s3proxy in unit tests, but cannot due to this incompatibility.

**Comment by andrewgaul** [comment]
This sounds reasonable; can you submit a pull request?

**Comment by benoj** [comment]
We have hit this problem too.

**Comment by andrewgaul** [comment]
jclouds 2.1.0 will upgrade to Guava 18 which will allow use of version 18-23:

https://issues.apache.org/jira/browse/JCLOUDS-1225
