### ISSUE TITLE
Does this support China Azure storage？

### ISSUE THREAD

**Issue by taroyutao** [gaul/s3proxy#231]
china azure storage has different endpoint, such as EndpointSuffix=core.chinacloudapi.cn. in common, we need to set EndpointSuffix, so that the request can point to china azure storage.

**Comment by andrewgaul** [comment]
@taroyutao S3Proxy needs support from the underlying Apache jclouds library.  Can you [file an issue](https://issues.apache.org/jira/browse/JCLOUDS) there?

**Comment by taroyutao** [comment]
I want to confirm whether it's support Azure China, not AWS China. Thanks!

**Comment by gaul** [comment]
@taroyutao This should work.  Can you test and report back?

**Comment by gaul** [comment]
Closed due to inactivity.  Please open if symptoms persist.
