### ISSUE TITLE
support object storage class

### ISSUE THREAD

**Issue by kahing** [gaul/s3proxy#234]
currently s3proxy allows `x-amz-storage-class` but ignores it and subsequent HEAD does not return the storage class. Instead the value should be propagated.

**Comment by andrewgaul** [comment]
Other providers like Azure, GCS, and Swift support storage policies at the container level instead of the object level like S3.  S3Proxy could special-case storage class for the filesystem and transient providers by storing this in user metadata.

**Comment by kahing** [comment]
Another frustration is S3Proxy returns it in LIST but not HEAD:

```xml
<?xml version='1.0' encoding='UTF-8'?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>goofys-test-97rfv1wrqkymmwss</Name><Prefix>empty_dir/</Prefix><MaxKeys>1</MaxKeys><Marker/><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>empty_dir/</Key><LastModified>2017-08-16T23:54:39Z</LastModified><ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag><Size>0</Size><StorageClass>STANDARD</StorageClass><Owner><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID><DisplayName>CustomersName@amazon.com</DisplayName></Owner></Contents></ListBucketResult>
```

**Comment by andrewgaul** [comment]
AWS head object only returns `x-amz-storage-class` when it is not `STANDARD`.

**Comment by kahing** [comment]
so weird but you are right!

**Comment by andrewgaul** [comment]
Amazon and Google both support object-level storage classes and Azure has a public preview of this feature.  S3Proxy can add support after jclouds resolves [JCLOUDS-1337](https://issues.apache.org/jira/browse/JCLOUDS-1337).
