### ISSUE TITLE
filesystem backend reports file as both file and directory

### ISSUE THREAD

**Issue by kahing** [gaul/s3proxy#240]
if I create a file:

```
$ aws s3 --endpoint http://127.0.0.1:8080/ cp README.md s3://goofys-bench/test_dir/file1
```

and try to head the object with directory blob suffix:

```
$ aws s3api --endpoint http://127.0.0.1:8080/  head-object --bucket goofys-bench --key test_dir/file1/
{
    "ContentType": "application/unknown", 
    "LastModified": "Wed, 30 Aug 2017 18:55:55 GMT", 
    "ContentLength": 0, 
    "ETag": "\"b773f1b79f5fc28aa2d0d231c714cca7\"", 
    "Metadata": {}
}
[s3proxy] D 08-30 00:23:04.212 S3Proxy-16 o.j.f.s.i.FilesystemStorageStrategyImpl:56 |::] goofys-bench - test_dir/file1/ is a directory
```

I expect to get 404. This is really a jclouds bug. https://github.com/jclouds/jclouds/blob/master/apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java#L331 should check that when we head file1/, the resulting file object is actually a directory before returning.

**Comment by gaul** [comment]
Fixed by 4f14a8419ff355718d3cd13ee0ae5e55e9a51e51.
