### ISSUE TITLE
s3proxy not to check timeskew when supplied non-current sys time to req

### ISSUE THREAD

**Issue by inevity** [gaul/s3proxy#245]
On goofys test case.
The minio and aws like s3 backend we have all check the timeskew.
But When use the proxys3 backend(config from goofys ,using the /tmp),it skip the timeskew.

Please ref goofys pull request https://github.com/kahing/goofys/pull/243.

**Comment by gaul** [comment]
Presently S3Proxy only checks the `Date` header for time skew:

https://github.com/gaul/s3proxy/blob/a09c9e1998599dbc573b08c5e82a2988fac8291f/src/main/java/org/gaul/s3proxy/S3ProxyHandler.java#L331

We also need to check `X-Amz-Date` header.

@inevity Could you investigate this?  I believe the format differs, 20111014T235959Z.

**Comment by inevity** [comment]
The request use the X-Amz-Date header format like X-Amz-Date: Fri, 03 Nov 2017 00:52:47 +0000.

**Comment by gaul** [comment]
I am mistaken, the `X-Amz-Date` header has a format like `Fri, 03 Nov 2017 00:52:47 +0000` when used as a header but `20130721T201207Z` when used a query parameter:

https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

**Comment by inevity** [comment]
I found that
when v2  header auth,header x-amz-date format is like Fri, 03 Nov 2017 00:52:47 +0000 ,
(ref  http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html for v2!
The value of the x-amz-date header must be in one of the RFC 2616 formats (http://www.ietf.org/rfc/rfc2616.txt). When an x-amz-date header is present in a request, the system will ignore any Date header when computing the request signature. )

when v2 query auth,no   x-amz-date query parameter.

when v4 header auth,,header x-amz-date format like 20130721T201207Z,
when v4 query auth, x-amz-date query parameter format like 20130721T201207Z
(ref: The time stamp must be in UTC and in the following ISO 8601 format: YYYYMMDD'T'HHMMSS'Z'. For example, 20150830T123600Z is a valid time stamp. Do not include milliseconds in the time stamp. from http://docs.aws.amazon.com/general/latest/gr/sigv4-date-handling.html)
(ref:https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html)
Note:https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html
mentioned that  use the 
Fri, 03 Nov 2017 00:52:47 +0000 format like,i think it is for v2.because it is not updated timely for v4.

All Date header format is like  Fri, 03 Nov 2017 00:52:47 +0000 

Now we ignore the web browser post auth.

**Comment by inevity** [comment]
So we should parse x-amz-date whether from v2 or v4. I have just patch it .but have beening stuck in debugging .

**Comment by inevity** [comment]
How to show debug log when mvn test?
I run single test
mvn -Dtest=org.gaul.s3proxy.AwsSdkTest#testAwsV4UrlSigning test
But only shou info ,no debug .
can you show your logback config or some other config?

**Comment by gaul** [comment]
You can add debug logs via `-DLOG_LEVEL=debug` or `-DLOG_LEVEL=trace`.

**Comment by inevity** [comment]
fix by https://github.com/gaul/s3proxy/pull/246
