### ISSUE TITLE
Support Wasabi 

### ISSUE THREAD

**Issue by RichardHerold** [gaul/s3proxy#248]
Wasabi is a popular s3 client that uses the same api calls as s3.

https://wasabi.com/wp-content/themes/wasabi/docs/API_Guide/index.html#t=topics%2FFrontMatter.htm

**Comment by gaul** [comment]
If Wasabi supports the S3 API then S3Proxy should just work.  Consults the storage backend examples:

https://github.com/gaul/s3proxy/wiki/Storage-backend-examples#s3-compatible-dreamobjects-etc

Do these instructions work for you?

**Comment by RichardHerold** [comment]
they do! thanks!
