### ISSUE TITLE
NPE in S3ProxyHandler

### ISSUE THREAD

**Issue by BrainLogic** [gaul/s3proxy#255]
Hi team!
Please, release the library with #251 fix. Right now, we cannot use the latest version with anonymous identity, get NPE in S3ProxyHandler on 400 line:
`if (authHeader.authenticationType == AuthenticationType.AWS_V2`
There is no condition for `anonymousIdentity`

**Comment by gaul** [comment]
Released 1.5.5.  I hoped to include a new jclouds release which has some compelling changes but its release has stalled.
