### ISSUE TITLE
Jetty dependency issues

### ISSUE THREAD

**Issue by massdosage** [gaul/s3proxy#263]
We have been trying to use S3Proxy to test code in a project which also uses Hive. Hive requires Jetty 7.x while S3Proxy requires Jetty 9.x. We have certain use cases where the tests are impossible to run as obviously only one version of Jetty can be on the classpath and we get various exceptions due to missing Jetty classes, incompatible method definitions etc. Would it be possible to shade and relocate the Jetty classes inside S3Proxy so the usage of it is effectively hidden from downstream users? I'm not a huge fan of shading but in situations like this it can be really helpful for allowing integration into projects which depend on different versions of a required library.

**Comment by gaul** [comment]
Previously someone requested shading Guava in #209.  In theory I am fine with shading both Guava and Jetty but in practice I have concerns about creating more complications.  I wonder if you can shade parts of S3Proxy dependencies in your application instead?  If not, let's see what the S3Proxy patch looks like.

**Comment by massdosage** [comment]
I think it's too late as by the time the jar hits us the s3proxy compiled code depends on "eclipse.jetty.foo" classes instead of "some.shaded.prefix.eclipse.jetty.foo". I'm not aware of a way of shading and relocating the contents of a jar that a project depends on as opposed to one that a project produces.

**Comment by gaul** [comment]
Do modules from Java 9 offer us anything here?  If not, please submit a pull request for shading Jetty.
