### ISSUE TITLE
Illegal key size Exception on accessing the Azure Blob

### ISSUE THREAD

**Issue by KYamunaSri** [gaul/s3proxy#268]
Hi Gaul

I have set up the S3proxy and am facing the below issue when i try to access my s3proxy. 
I got a HTTP 500 response and on adding up few stack traces, I end up with the Illegal Key size issue.

11:45:35.659 [S3Proxy-Jetty-16 - /] DEBUG jclouds.headers - >> Authorization: SharedKeyLite dcmpoc01:SzfJUaiDKNeJEodYVM65XMfPkBIfwLONBDisqktPI+U=
11:45:38.097 [S3Proxy-Jetty-16 - /] ERROR org.gaul.s3proxy.Main - org.jclouds.http.HttpResponseException: java.security.InvalidKeyException: Illegal key size connecting to GET https://xxxx.blob.core.windows.net/xxxx?restype=container&comp=list&include=metadata HTTP/1.1
11:45:38.097 [S3Proxy-Jetty-16 - /] ERROR org.gaul.s3proxy.Main - 

Can you please throw some pointers on this?

**Comment by KYamunaSri** [comment]
This was an issue with the Java version.

**Comment by gaul** [comment]
@KYamunaSri Can you share more about your workaround, e.g, which Java version has a problem and which one works?

**Comment by KYamunaSri** [comment]
Hi Gaul

The java folder I  had did not have the Security folder in it. I
reinstalled Java 8 and then it worked.

Regards
Yamuna Sri
