### ISSUE TITLE
S3ProxyRule - The AWS access key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by MkJha** [gaul/s3proxy#278]
As provided in sample :

```java
AmazonS3 s3Client = AmazonS3ClientBuilder
            .standard()
            .withCredentials(
              new AWSStaticCredentialsProvider(
                new BasicAWSCredentials(s3Proxy.getAccessKey(), 
                                        s3Proxy.getSecretKey())))
            .withEndpointConfiguration(
              new EndpointConfiguration(s3Proxy.getUri().toString(), 
                                        Regions.US_EAST_1.getName()))
            .build();
```

Rather than this , i am creating client using the below snippet(this is how my code client is defined):

```java
 AmazonS3 s3Client = AmazonS3ClientBuilder
    	            .standard()
    	            .withCredentials(
    	              new AWSStaticCredentialsProvider(
    	                new BasicAWSCredentials(S3_PROXY_RULE.getAccessKey(), 
    	                		S3_PROXY_RULE.getSecretKey())))
    	            .withRegion("us-east-1")
    	            .build();
```

In this case its throwing the exception AmazonS3Exception with the message "The AWS access key Id you provided does not exist in our records."

**Comment by gaul** [comment]
@MkJha This example creates a client with S3Proxy default credentials but using the default AWS endpoint.  If you want to use S3Proxy, you also need to provide the endpoint:

```java
new EndpointConfiguration(s3Proxy.getUri().toString(), Regions.US_EAST_1.getName()))
```

**Comment by MkJha** [comment]
@gaul  That was my bad, I could have realized this before raising this issue.  I realized this later, without giving the end point,  it is impossible to divert the request to aws proxy.  In absence of end point , request would always hit the real aws.  Thanks for your attention.

**Comment by tkadarla** [comment]
I am using aws cli and getting the same error.. Below is what I ran:
aws s3 cp /tmp/test.txt s3://<bucket_name> --endpoint-url 'http://<loadbalancer-url>:443' --region us-east-2
