### ISSUE TITLE
Junit5: support jupiter engine

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [gaul/s3proxy#288]
Are there plans to support `junit5` via the extension mechanism? Do you need support (I might be able to help, though I did not yet looked into details)

**Comment by gaul** [comment]
I am not familiar with this mechanism; could you explain this feature request more completely?  I am unlikely to implement it but will review pull requests.

@ddcprg @massdosage Related to your existing JUint @Rule functionality?

**Comment by ddcprg** [comment]
Hi @gaul / @ThanksForAllTheFish  as of Junit 5 rules have been replaced with callbacks and extensions. At first glance it seems like it wouldn't take a lot of effort to add an extension for Junit 5. I could dig a bit to understand better what it's needed an then purpose a change. I'm also happy to leave this with @massdosage if he prefer to take it on - I'll catch up with him.

**Comment by massdosage** [comment]
A while back I looked at what would be required to replace JUnit4 rules with the JUnit5 equivalents and like @ddcprg concluded that it should't take too much effort but at the time JUnit5 was still very new and we had no plans to move to it. It's more mature now but we still don't have a compelling reason to move over to it so we probably won't implement this ourselves just yet but I'd be happy to review pull requests.
