### ISSUE TITLE
Your project gaul/s3proxy is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [gaul/s3proxy#291]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  ch.qos.logback logback-classic (pom.xml)
  version: 1.2.3

  Jira issues:
  missing log files and log entries when using SizeAndTimeBasedRollingPolicy 
  affectsVersions:1.2.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1361?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by gaul** [comment]
I do not find this bug report valuable and request that you do not send further automated issues.  In this case, there is no released version of logback which includes a fix.  Further, it is not obvious that this issue has any particular criticality that merits spamming random projects.
