### ISSUE TITLE
Access Denied issue when connect to Azure Blob storage

### ISSUE THREAD

**Issue by bajiip** [gaul/s3proxy#306]
Dear Friends,

I have downloaded the S3Proxy app and modified the docker ENV variables to point to Azure Blob storage. Below is my ENV configuration in the docker file. 

ENV \
    LOG_LEVEL="trace" \
    S3PROXY_AUTHORIZATION="aws-v2" \
    S3PROXY_IDENTITY="local-identity" \
    S3PROXY_CREDENTIAL="local-credential" \
    S3PROXY_CORS_ALLOW_ALL="false" \
    S3PROXY_CORS_ALLOW_ORIGINS="" \
    S3PROXY_CORS_ALLOW_METHODS="" \
    S3PROXY_CORS_ALLOW_HEADERS="" \
    S3PROXY_IGNORE_UNKNOWN_HEADERS="false" \
    JCLOUDS_PROVIDER="azureblob" \
    JCLOUDS_ENDPOINT="https://xxxxxx.blob.core.windows.net/" \
    JCLOUDS_REGION="" \
    JCLOUDS_REGIONS="us-east-1" \
    JCLOUDS_IDENTITY="xxxxxx" \
    JCLOUDS_CREDENTIAL="xxxxxxxxx” \
    JCLOUDS_KEYSTONE_VERSION="" \
    JCLOUDS_KEYSTONE_SCOPE="" \
    JCLOUDS_KEYSTONE_PROJECT_DOMAIN_NAME=""

When I run the docker container and navigate to the URL, I am getting an error like below. Can anyone help me to understand what is the issue and how to fix it?. 
Note: Using the Azure storage account and the Key, I am able to access the Azure storage in the Microsoft Azure Storage Explorer.

<Error>
<Code>AccessDenied</Code>
<Message>403 AccessDenied Forbidden</Message>
<RequestId>4442587FB7D0A2F9</RequestId>
</Error>

**Comment by gaul** [comment]
What do your trace-level logs say?

**Comment by bajiip** [comment]
Below is my log.
[s3proxy] I 06-25 03:45:44.220 main o.g.s.o.e.jetty.server.Server:379 |::] Started @2161ms
[s3proxy] D 06-25 03:45:51.637 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:286 |::] request: Request(GET /)@66db8a9d
[s3proxy] D 06-25 03:45:51.640 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Upgrade-Insecure-Requests
: 1
[s3proxy] D 06-25 03:45:51.641 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept-Language: en-US,en
;q=0.9
[s3proxy] D 06-25 03:45:51.642 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Host: localhost:8080
[s3proxy] D 06-25 03:45:51.643 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept-Encoding: gzip, de
flate, br
[s3proxy] D 06-25 03:45:51.644 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: User-Agent: Mozilla/5.0 (
Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
[s3proxy] D 06-25 03:45:51.644 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Connection: keep-alive
[s3proxy] D 06-25 03:45:51.645 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept: text/html,applica
tion/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
[s3proxy] D 06-25 03:45:51.646 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Cache-Control: max-age=0
[s3proxy] D 06-25 03:45:51.656 S3Proxy-Jetty-14 o.gaul.s3proxy.S3ProxyHandler:2838 |::] 403 AccessDenied Forbidden {}
[s3proxy] D 06-25 03:45:51.786 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:286 |::] request: Request(GET /favicon.ico
)@66db8a9d
[s3proxy] D 06-25 03:45:51.789 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept-Language: en-US,en
;q=0.9
[s3proxy] D 06-25 03:45:51.790 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Host: localhost:8080
[s3proxy] D 06-25 03:45:51.792 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept-Encoding: gzip, de
flate, br
[s3proxy] D 06-25 03:45:51.793 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Referer: http://localhost
:8080/
[s3proxy] D 06-25 03:45:51.795 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: User-Agent: Mozilla/5.0 (
Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
[s3proxy] D 06-25 03:45:51.797 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept: image/webp,image/
apng,image/*,*/*;q=0.8
[s3proxy] D 06-25 03:45:51.798 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Connection: keep-alive
[s3proxy] D 06-25 03:45:51.799 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Cache-Control: no-cache
[s3proxy] D 06-25 03:45:51.803 S3Proxy-Jetty-15 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Pragma: no-cache
[s3proxy] T 06-25 03:45:51.823 S3Proxy-Jetty-15 o.j.r.i.InvokeHttpMethod:47 |::] >> converting GetContainerACL
[s3proxy] D 06-25 13:33:57.572 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:286 |::] request: Request(GET /)@13cb35da
[s3proxy] D 06-25 13:33:57.572 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Upgrade-Insecure-Requests
: 1
[s3proxy] D 06-25 13:33:57.572 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept-Language: en-US,en
;q=0.9
[s3proxy] D 06-25 13:33:57.572 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Host: localhost:8080
[s3proxy] D 06-25 13:33:57.573 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept-Encoding: gzip, de
flate, br
[s3proxy] D 06-25 13:33:57.573 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: User-Agent: Mozilla/5.0 (
Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
[s3proxy] D 06-25 13:33:57.573 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Connection: keep-alive
[s3proxy] D 06-25 13:33:57.573 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept: text/html,applica
tion/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
[s3proxy] D 06-25 13:33:57.573 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Cache-Control: max-age=0
[s3proxy] D 06-25 13:33:57.574 S3Proxy-Jetty-17 o.gaul.s3proxy.S3ProxyHandler:2838 |::] 403 AccessDenied Forbidden {}
[s3proxy] D 06-25 13:33:57.604 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:286 |::] request: Request(GET /favicon.ico
)@13cb35da
[s3proxy] D 06-25 13:33:57.605 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept-Language: en-US,en
;q=0.9
[s3proxy] D 06-25 13:33:57.605 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Host: localhost:8080
[s3proxy] D 06-25 13:33:57.605 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept-Encoding: gzip, de
flate, br
[s3proxy] D 06-25 13:33:57.606 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Referer: http://localhost
:8080/
[s3proxy] D 06-25 13:33:57.607 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: User-Agent: Mozilla/5.0 (
Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
[s3proxy] D 06-25 13:33:57.607 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Accept: image/webp,image/
apng,image/*,*/*;q=0.8
[s3proxy] D 06-25 13:33:57.608 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Connection: keep-alive
[s3proxy] D 06-25 13:33:57.608 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Cache-Control: no-cache
[s3proxy] D 06-25 13:33:57.608 S3Proxy-Jetty-18 o.gaul.s3proxy.S3ProxyHandler:311 |::] header: Pragma: no-cache
[s3proxy] T 06-25 13:33:57.610 S3Proxy-Jetty-18 o.j.r.i.InvokeHttpMethod:47 |::] >> converting GetContainerACL

**Comment by gaul** [comment]
It looks like you are trying to access S3Proxy from your web browser instead of an S3 client.  How did you configure the `s3proxy.authorization` property?  If it is set to `none` the web browser should work, although I recommend using authorization with a real client like the AWS CLI.

**Comment by bajiip** [comment]
Thanks. It works after i set to s3proxy.authorization=none.

**Comment by pppaulpeter** [comment]
> Thanks. It works after i set to s3proxy.authorization=none.

Hi,
may i know how do you test it?
this is my log when i run the proxy container
 docker run --publish 80:80 --env S3PROXY_AUTHORIZATION=none 1bbcc87a6733
[s3proxy] I 09-24 20:42:19.034 main o.g.s.CrossOriginResourceSharing:95 |::] CORS allowed origins: []
[s3proxy] I 09-24 20:42:19.037 main o.g.s.CrossOriginResourceSharing:96 |::] CORS allowed methods: []
[s3proxy] I 09-24 20:42:19.037 main o.g.s.CrossOriginResourceSharing:97 |::] CORS allowed headers: []
[s3proxy] I 09-24 20:42:19.045 main o.g.s.o.eclipse.jetty.util.log:170 |::] Logging initialized @1108ms to org.gaul.shaded.org.eclipse.jetty.util.log.Slf4jLog
[s3proxy] I 09-24 20:42:19.100 main o.g.s.o.e.jetty.server.Server:375 |::] jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 1.8.0_212-b04
[s3proxy] I 09-24 20:42:19.168 main o.g.s.o.e.j.s.AbstractConnector:331 |::] Started ServerConnector@5d2a4eed{HTTP/1.1, (http/1.1)}{127.0.0.1:80}
[s3proxy] I 09-24 20:42:19.168 main o.g.s.o.e.jetty.server.Server:415 |::] Started @1230ms
