### ISSUE TITLE
Enabling s3proxy trace logs should enable jclouds trace logging

### ISSUE THREAD

**Issue by timuralp** [gaul/s3proxy#308]
When s3proxy trace logging is enabled, the jclouds logging should be enabled as well. It's most certainly going to be required to understand whether there is an issue in the actual response from the provider vs s3proxy translation of the response.

**Comment by gaul** [comment]
At least in my tests, enabling s3proxy trace logging also enables jclouds debug logging.

**Comment by timuralp** [comment]
I checked that I observe the same behavior.
