### ISSUE TITLE
v2-or-v4 in example docs

### ISSUE THREAD

**Issue by tivvit** [gaul/s3proxy#312]
Hi,

Since `v2-or-v4` is default in the docker image (https://github.com/gaul/s3proxy/commit/456f7c7a0a20f4a35618414ddf1b3037d6bb113b) I think it should be default in the backend examples (https://github.com/gaul/s3proxy/wiki/Storage-backend-examples) because it is a reasonable default and it is not much mentioned in the docs.
If you think that is a good idea I will prepare PR.

**Comment by ticapix** [comment]
I was stucked for days with this. I updated the wiki page for AWS with hadoop https://github.com/gaul/s3proxy/wiki/Client-compatibility-list#aws-sdk-for-hadoopspark

**Comment by gaul** [comment]
These `aws-v2` examples date back to before S3Proxy supported v4 when the only alternative was `none`.  Agree that `aws-v2-or-v4` would be more appropriate; could you update them?

**Comment by ticapix** [comment]
s/aws-v2/aws-v2-or-v4/g on https://github.com/gaul/s3proxy/wiki/Storage-backend-examples

**Comment by gaul** [comment]
Thank you for your contributions @ticapix!
