### ISSUE TITLE
s3proxy don't accept x-amz-te header

### ISSUE THREAD

**Issue by pip-765** [gaul/s3proxy#327]
I'm using awssdk s3client (https://mvnrepository.com/artifact/software.amazon.awssdk/s3) and call getObject() method to get an object on s3proxy, but status code 501 is returned because s3proxy denies x-amz-te header which s3client automatically add.

s3proxy's log (with -DLOG_LEVEL=debug) is following:

> [s3proxy] D 07-29 06:18:10.155 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:287 |::] request: Request(GET /somebucket/somefile.txt)@16a79473
> [s3proxy] D 07-29 06:18:10.155 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: Authorization: AWS4-HMAC-SHA256 Credential=access_key/20200729/ap-northeast-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;host;x-amz-content-sha256;x-amz-date;x-amz-te, Signature=6d547b2ffbd61b017ee70510e42b040b5e69d2273e305e2608fdbb5cc9be8002
> [s3proxy] D 07-29 06:18:10.155 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: x-amz-content-sha256: UNSIGNED-PAYLOAD
> [s3proxy] D 07-29 06:18:10.155 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: X-Amz-Date: 20200729T061810Z
> [s3proxy] D 07-29 06:18:10.155 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: x-amz-te: append-md5
> [s3proxy] D 07-29 06:18:10.156 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: User-Agent: aws-sdk-java/2.10.65 Linux/3.10.0-1062.12.1.el7.x86_64 OpenJDK_64-Bit_Server_VM/11.0.5+10 Java/11.0.5 vendor/Oracle_Corporation io/sync http/Apache
> [s3proxy] D 07-29 06:18:10.156 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: Connection: Keep-Alive
> [s3proxy] D 07-29 06:18:10.156 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: Host: s3proxy-internal
> [s3proxy] D 07-29 06:18:10.156 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: amz-sdk-invocation-id: fb3cd79c-2993-b30d-d95b-7190263c329b
> [s3proxy] D 07-29 06:18:10.156 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:312 |::] header: amz-sdk-retry: 0/0/500
> [s3proxy] E 07-29 06:18:10.156 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:622 |::] Unknown header x-amz-te with URI /somebucke/somefile.txt
> [s3proxy] D 07-29 06:18:10.156 S3Proxy-Jetty-20 o.gaul.s3proxy.S3ProxyHandler:2862 |::] sendSimpleErrorResponse: 501 NotImplemented A header you provided implies functionality that is not implemented. {}

S3ProxyHandler seems to restrict request headers starting with x-amz- .

**Comment by gaul** [comment]
Can you share how you invoke `getObject`?  `ENABLE_CHECKSUM_REQUEST_HEADER` appears to be a new, undocumented header which allows appending the MD5 to the response after the data payload.  It seems odd for this to be the default behavior.

**Comment by pip-765** [comment]
Thank you for your response.

I tried to run folloiwng progmram with s3client version 2.10 : 

`
public class Main {

	public static void main(String[] args) throws Exception {
		final AwsCredentialsProvider provider = new AwsCredentialsProvider() {
					@Override
					public AwsCredentials resolveCredentials() {
						return new AwsCredentials() {
							@Override
							public String secretAccessKey() {
								return "secret_access_key";
							}
							
							@Override
							public String accessKeyId() {
								return "access_key";
							}
						};
					}
				};
		
		S3Client client = S3Client.builder()
				.serviceConfiguration(b -> { 
					b.pathStyleAccessEnabled(true);
				})
				.credentialsProvider(provider)
				.region(Region.of("s3proxy"))
				.endpointOverride(new URI("http://s3proxy"))
				.build();

		ResponseBytes<GetObjectResponse> response =
				client.getObject(GetObjectRequest.builder()
						.bucket("somebucket")
						.key("somefile.txt")
						.build(),
						ResponseTransformer.toBytes());
`

Although I'm not programming about request header in particular, s3client seems to append x-amz-te header in default. 
However the problem is that check sum is enable, so I will try to set checksumValidationEnabled in serviceConfigration of s3client to false.

**Comment by pip-765** [comment]
When I set checksumValidationEnabled to false, s3client no longer adds x-amz-te header. Thank you for your tips.

`
		S3Client client = S3Client.builder()
				.serviceConfiguration(b -> { 
					b.pathStyleAccessEnabled(true);
					b.checksumValidationEnabled(false); // <- add
				})
				.credentialsProvider(provider)
				.region(region)
				.endpointOverride(endpoint)
				.build();

`

**Comment by gaul** [comment]
Hopefully AWS changes the default.  Otherwise S3Proxy must implement this header for compatibility.

**Comment by gaul** [comment]
Fixed by 544a863f965290f1ea91db02d68e149bb9980e44 in #414.
