### ISSUE TITLE
Missing CORS header in the response

### ISSUE THREAD

**Issue by tatiesmars** [gaul/s3proxy#343]
Hello,

First, thank you for the project, it is the only S3 proxy available that we found that support a progress bar while downloading, which help us!

We setup the s3proxy the following way
```
    - S3PROXY_AUTHORIZATION=none
    - S3PROXY_CORS_ALLOW_ALL=true
    - S3PROXY_CORS_ALLOW_ORIGINS=*
    - S3PROXY_CORS_ALLOW_METHODS=GET PUT POST HEAD DELETE
    - S3PROXY_CORS_ALLOW_HEADERS=*
    - JCLOUDS_PROVIDER=s3
```

As far as I understand CORS should allow any origins with any headers and any methods.

Unfortunately, all the CORS header are missing from the response

Here is the curl command we use:
`curl  -H "Access-Control-Request-Method: GET" -H "Origin: http://localhost" --head http://localhost/<bucket_name>/open-sans-3.ttf`
 
And the response we got:
```
Date: Wed, 13 Jan 2021 09:14:19 GMT
x-amz-request-id: XXXXXXXXXXXXXXX
Content-Type: binary/octet-stream
ETag: "XXXXXXXXXXXXXXX"
Last-Modified: Tue, 29 Dec 2020 16:30:17 GMT
x-amz-storage-class: STANDARD
Content-Length: 28100
Server: Jetty(9.2.z-SNAPSHOT)
```

I can confirm that when we are curling directly the bucket with the same command, the following header will be in the response:

```
access-control-allow-origin: *
access-control-allow-methods: GET, HEAD, DELETE, PUT, POST
access-control-expose-headers: Access-Control-Allow-Origin
```

I am confused if we are doing something wrong, if it's a bug or a missing feature at the moment.

**Comment by gaul** [comment]
@reimannf Could you look at this issue?

**Comment by Rotemy** [comment]
@gaul @reimannf Thanks for this amazing library. It would be great to get an answer quickly as our users encounter problems loading fonts as we don't have a workaround for this issue.

Thanks!

**Comment by reimannf** [comment]
As per README.md, currently there is only support for:
> Actual CORS requests are supported for GET, PUT and POST methods.

But I can check whether it is an easy fix to adding this for Blob HEADs.

**Comment by tatiesmars** [comment]
@reimannf 
Thank for you reply,

AFAIK the HEAD request is the request made by browser to verify CORS.

As described by this doc, HEAD is pretty much the same as a GET request.

**Comment by reimannf** [comment]
Ok, it seems there is a misunderstanding here. The CORS pre-flight request via `OPTION` is supported. What is not support atm, that all methods will include the CORS response headers when doing the actual request after the preflight.
Your example configures `HEAD` as allowed method for CORS, although `s3proxy` does not include the headers in a `HEAD` response. 

I will try to file a PR with 2 things in the next days:

1. Add a validation of the configured allowed methods against the supported ones
2. Try to add the CORS response headers for `HEAD` and `DELETE`

**Comment by tatiesmars** [comment]
Thanks for clearing this out, after a bit of testing I think I understand better the problem we are facing.

I am using now the following curl command to debug it:
```
curl -H "Origin: http://localhost" -H "Access-Control-Request-Method: GET" -X OPTIONS -I <URL>
```
and those are the headers received:
```
HTTP/1.1 200 OK
Date: Wed, 20 Jan 2021 08:46:32 GMT
x-amz-request-id: 4442587FB7D0A2F9
Access-Control-Allow-Origin: http://localhost
Vary: Origin
Access-Control-Allow-Methods: GET, PUT, POST
Content-Length: 0
Server: Jetty(9.2.z-SNAPSHOT)
```
The problem is that I set `S3PROXY_CORS_ALLOW_ORIGINS`to `*`, I would expect the header `Access-Control-Allow-Origin` to be equal to `*` but instead it got set to the value of the origins request header. 

Examples:

```
 curl -H "Origin: foo" -H "Access-Control-Request-Method: GET" -X OPTIONS -I <URL>
 
 HTTP/1.1 200 OK
Date: Wed, 20 Jan 2021 08:58:15 GMT
x-amz-request-id: 4442587FB7D0A2F9
Access-Control-Allow-Origin: foo
Vary: Origin
Access-Control-Allow-Methods: GET, PUT, POST
Content-Length: 0
Server: Jetty(9.2.z-SNAPSHOT)
```
 
```
 curl -H "Origin: this is not working" -H "Access-Control-Request-Method: GET" -X OPTIONS -I <URL>
 HTTP/1.1 200 OK
Date: Wed, 20 Jan 2021 08:59:28 GMT
x-amz-request-id: 4442587FB7D0A2F9
Access-Control-Allow-Origin: this is not working
Vary: Origin
Access-Control-Allow-Methods: GET, PUT, POST
Content-Length: 0
Server: Jetty(9.2.z-SNAPSHOT)
 ```

**Comment by reimannf** [comment]
Well, the specification for CORS is not accurate enough at exactly that point. It does not state clearly whether the exact configured CORS rule should be returned in the `Access-Control-Allow-Origin` header or the result of the evaluation. Technical it should not matter as you do the preflight for a `GET` request for Origin `http://localhost` and you get a `200`, which should be enough for the client to do the actual `GET`.

**Comment by Rotemy** [comment]
@reimannf The issue is that we are pointing a CDN to the proxy server and then the file is cached with the headers of the first request that was made for the file.

So if foo.com called that file for the first time, even if foo2.com will ask that file from the CDN the headers will have foo.com as they are cached.

This is why we need the proxy server to return *.

**Comment by reimannf** [comment]
ok, in that scenario the issue is more related, that the response is missing the `VARY` header including the CORS headers. I think I will rather include that in the responses.

**Comment by Rotemy** [comment]
@reimannf In that case, the request will not be cached by the CDN and every time a client will ask for the file it will be fetched from the proxy server.

Maybe you can add `S3PROXY_CORS_ALLOW_ALL_WILDCARD` and allow the developers that use this library to set the wildcard?

**Comment by reimannf** [comment]
I did a little bit further reading regarding the caching use case and also tried the original behaviour directly against AWS S3. 
My preliminary opinion is, that you are right and I might need to change the current responses from s3proxy to match AWS S3. Will update here asap.
