### ISSUE TITLE
release binary should have the suffix .jar

### ISSUE THREAD

**Issue by waffel** [gaul/s3proxy#348]
I have downloaded latest release (not source code) and got an file without any suffix ("s3proxy"). 

Because it is an jar file (I can start it via 'java -jar s3proxy').

My suggestion is to name the download file also 's3proxy.jar'.

**Comment by gaul** [comment]
This is an executable jar that should be `chmod +x` as described in the README.  If you want to interact with S3Proxy as a Java program you should use the jar file on Maven Central.

**Comment by waffel** [comment]
OK .. I'm running under Windows :-) ... so no 'chmod +x' ... but ok for me ... was just a minor hint
