### ISSUE TITLE
Issue serving text files

### ISSUE THREAD

**Issue by dcarrion87** [gaul/s3proxy#395]
When uploading text files such as JS or CSS files to s3proxy it seems being uploaded as binary and web browsers unable to interpret them.

Is this expected behaviour?

<img width="505" alt="Screen Shot 2021-11-30 at 9 00 40 am" src="https://user-images.githubusercontent.com/2899172/143949700-5dbea59a-ab27-4275-b91c-f0b0026a26ad.png">

**Comment by gaul** [comment]
This is unexpected.  How did you create this object, e.g., upload via AWS CLI?  Did you use some kind of gzip or other transformation?

**Comment by dcarrion87** [comment]
Aah yep that's what it was. It was uploading GZIP compressed. Sorry about that.

**Comment by gaul** [comment]
Does the behavior differ from AWS?  Perhaps S3Proxy does not interpret the compressed Content-Type?

**Comment by dcarrion87** [comment]
That seems to be the case.

**Comment by gaul** [comment]
Could you provide a test case that reproduces the symptoms, e.g., using the AWS CLI?  s3-tests should have a test case for this too although I don't know if it does currently.
