### ISSUE TITLE
Java 17 compatibility

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#396]
S3Proxy relies on an older version of Guice which does not allow some illegal reflective accesses.  jclouds 2.5.0 will address this via [JCLOUDS-1586](https://issues.apache.org/jira/browse/JCLOUDS-1586) although we could override the version in S3Proxy if we run a release sooner.

**Comment by gaul** [comment]
The primary motivation for this is to allow macOS to use xattr with the filesystem storage backend.

**Comment by xgourmandin** [comment]
Checking to know if this one is still wanted.
I've tested successfully the project with Java 17 by updating manually guice to 5.0.1 in S3Proxy.
But it seems that Jcloud 2.5.0 is ready to be delivered as all issues are fixed.
Do you still want this to release this earlier, or are we waiting for the next JCloud release ?

**Comment by gaul** [comment]
Let me release jclouds 2.5.0 then I will run another S3Proxy release.
