### ISSUE TITLE
S3Proxy 2.0.0

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#410]
Apache jclouds will release 2.5.0 this month and I would like to also release S3Proxy 2.0.0.  I will try to review the open PRs.

**Comment by gaul** [comment]
Merged jclouds 2.5.0.  I plan to run a release next weekend.  Please help test this before the release!

**Comment by vladimirfx** [comment]
New `S3ProxyExtension` requires set credentials even in NONE mode:

```kotlin
S3ProxyExtension.builder()
        .withCredentials(AuthenticationType.NONE, "dummy", "dummy")
        .build()
```

In `S3ProxyExtension` `AuthenticationType.NONE` is default but the service is crashed with NPE when no credentials are set.

**Comment by gaul** [comment]
Please open a new issue for this symptom.  PRs welcome but I do not consider this a blocker.  @xgourmandin related to #347?
