### ISSUE TITLE
 Error: Unknown header x-amz-te with URI (Camel aws2-s3)

### ISSUE THREAD

**Issue by radekcz** [gaul/s3proxy#414]
When I try to use s3proxy for testing aws2-s3 component from Apache Camel, I keep getting Error:

`[S3Proxy-Jetty-46] ERROR org.gaul.s3proxy.S3ProxyHandler - Unknown header x-amz-te with URI`

I know this issue can be solved by the configuration of s3-client but when I use Camel aws2-s3 component, I'm not able to change this setting. So is it possible to implement/ignore this attribute on s3proxy side? Thanks a lot.

Maybe related to: https://github.com/aws/aws-sdk-java-v2/issues/1974

**Comment by gaul** [comment]
This seems like an unfortunate default behavior from your client.  I believe that this is related to [additional checksum algorithms](https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/).  Ideally S3Proxy would add full support for this, at least enforcing the checksum during upload.  But ignoring the header is probably a sufficient workaround.

**Comment by juangburgos** [comment]
Same here:
```
[s3proxy] E 11-08 19:22:29.118 S3Proxy-Jetty-12 o.gaul.s3proxy.S3ProxyHandler:640 |::] Unknown header x-amz-user-agent with URI 
```
> unfortunate default behavior from your client:

Unfortunatelly, that would be the official from AWS:
```
X-Amz-User-Agent: aws-sdk-js/2.1161.0 promise
```

**Comment by Blackfaded** [comment]
Having the same issue as [juangburgos](https://github.com/juangburgos)

**Comment by juangburgos** [comment]
> Having the same issue as [juangburgos](https://github.com/juangburgos)

`s3proxy.ignore-unknown-headers=true` helped

**Comment by Blackfaded** [comment]
> > Having the same issue as [juangburgos](https://github.com/juangburgos)
> 
> `s3proxy.ignore-unknown-headers=true` helped

Thanks a lot!
Made the config via docker-compose with
```yaml
- S3PROXY_IGNORE_UNKNOWN_HEADERS=true
```

That also worked
