### ISSUE TITLE
Jetty 9.4 is EOL as of this month

### ISSUE THREAD

**Issue by ryanfaircloth** [gaul/s3proxy#422]
Because Jetty 9.4 is EOL the version of jetty used should be upgraded to 10 or preferably 11

**Comment by gaul** [comment]
Jetty 10 will increase the [Java version requirement from 8 to 11](https://www.eclipse.org/jetty/).  This is not a blocker but usually annoying for some subset of the community.

**Comment by ryanfaircloth** [comment]
Fair but with a important component going EOL that will be a blocker for many for compliance /security reasons
