### ISSUE TITLE
Jakarta based release

### ISSUE THREAD

**Issue by vladimirfx** [gaul/s3proxy#467]
Please consider publishing the first Jakarta-based release.

**Comment by gaul** [comment]
Do you mean publishing a release containing #422?  I plan to run another jclouds release before releasing S3Proxy 2.1.0.

**Comment by vladimirfx** [comment]
Super, thank you!

**Comment by gaul** [comment]
I am traveling for a few weeks but you can use the latest 2.1.0-SNAPSHOT in the mean-time.

**Comment by vladimirfx** [comment]
Just checked 2.1.0-SNAPSHOT in tests - it is all green. Waiting for release. Than you again!

**Comment by aharin** [comment]
Any plans to publish the 2.1.0 release?

**Comment by paolobazzi** [comment]
What's the current plan about a Jakarta-based release for s3proxy?

**Comment by gaul** [comment]
I believe that 2.1.0 release addressed this issue.  Please reopen if I misunderstand this.
