### ISSUE TITLE
Unable to list more than 999 files

### ISSUE THREAD

**Issue by davidp1404** [gaul/s3proxy#477]
Hello, in our use case we have to list more than 1000 objects in a bucket but due to the hard limit found in S3ProxyHandler.java file it seems to be not possible. Could you please share why this limit is hard coded?.
![image](https://user-images.githubusercontent.com/58428863/207915287-8d6661a3-61d4-4534-9f92-cbae1a45105c.png)

Scenario:
- Azure blob backend
- AKS running latest s3proxy image

**Comment by gaul** [comment]
The S3 protocol only allows 1000 keys by default:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html

I believe that Azure and other object store protocols have similar limits.  You should call list in a loop and use the `marker` returns from previous calls as input to subsequent calls.

**Comment by davidp1404** [comment]
Thanks @gaul, clear now.
