### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#479]
Looks like some rot within s3-tests:

> AttributeError: module 'collections' has no attribute 'Callable'

Seen in #464.

**Comment by gaul** [comment]
@timuralp the Containerize steps fails with:

```
 Failed to get manifest docker.io/library/master:latest: Unauthorized [http 401]: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"library/master","Action":"pull"}]}]}
```

https://github.com/gaul/s3proxy/actions/runs/5020361449/jobs/9001824708#step:10:29

Do you think this is an easy fix or should we just disable the Docker push?

**Comment by timuralp** [comment]
I need to investigate this a bit. Will try to look into this tonight/tomorrow. I don't understand why the login doesn't work.
