### ISSUE TITLE
Possibility to use Managed Identities instead of SA-key

### ISSUE THREAD

**Issue by Hackmeat** [gaul/s3proxy#493]
Is there a way currently to use Azure Managed Identities on s3proxy? 
I don't want to use the Storage Account key due to security reasons and rather add this in Kustomize

`aadpodidbinding: name-of-managed-identity`

Anyone having a workaround for this or will there be a feature like this in the future?

**Comment by gaul** [comment]
Is this the same issue as or related to [JCLOUDS-1574](https://issues.apache.org/jira/browse/JCLOUDS-1574) and #352?

**Comment by Hackmeat** [comment]
oh yeah its the same, didnt see that one. ty
