### ISSUE TITLE
Unknown header x-amz-api-version with URI /bucketname/filetobedeleted 

### ISSUE THREAD

**Issue by Sunithassunagad** [gaul/s3proxy#497]
I am trying to delete a file using the client cpp aws sdk 

Please find the log below 

Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.794 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:300 |::] request: **Request(DELETE http://127.0.0.1:8085/bucketname/filetobedeleted)@47a6d831**
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.794 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: Accept: */*
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: x-amz-date: 20230208T174826Z
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: Connection: Upgrade, HTTP2-Settings
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: User-Agent: aws-sdk-cpp/1.8.7 Linux/4.18.0-425.10.1.el8_7.x86_64 x86_64 GCC/8.5.0
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: Host: 127.0.0.1:8085
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: Upgrade: h2c
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: Authorization: AWS4-HMAC-SHA256 Credential=AKI*************4/20230208/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date, Signature=b1dfeb722600598b4a14e1a1183ccfe962850d7ce8b26e43aece2f0cf8d5db1a
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: x-amz-api-version: 2006-03-01
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: amz-sdk-invocation-id: 8EC2144C-09FA-4A3D-BFE6-ACCDAD00900C
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: amz-sdk-request: attempt=1
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.795 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: content-type: application/xml
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.796 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:325 |::] header: HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] E 02-08 18:48:26.796 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:641 |::] **Unknown header x-amz-api-version with URI /bucketname/filetobedeleted**
Feb 08 18:48:26 box-cpw java[4019]: [s3proxy] D 02-08 18:48:26.796 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:2948 |::] sendSimpleErrorResponse: 501 NotImplemented A header you provided implies functionality that is not implemented. {}

**Comment by alifirat** [comment]
Did you try to configure the proxy to ignore unknown headers ?
