### ISSUE TITLE
Unable to setup middleware

### ISSUE THREAD

**Issue by DaRacci** [gaul/s3proxy#521]
For the PR #378 Can someone explain how to actually use this, there was never a middleware section added to the wiki for it and I can't seem to figure it out.

**Comment by gaul** [comment]
@timuralp could you help with this?

**Comment by timuralp** [comment]
Somehow I forgot to add the wiki page -- apologies. @DaRacci I added a page describing how this works here: https://github.com/gaul/s3proxy/wiki/Middleware-bucket-locator

**Comment by gaul** [comment]
@timuralp please add a link to https://github.com/gaul/s3proxy#middlewares so we can close this issue.

**Comment by DaRacci** [comment]
> Somehow I forgot to add the wiki page -- apologies. @DaRacci I added a page describing how this works here: https://github.com/gaul/s3proxy/wiki/Middleware-bucket-locator

Cheers
