### ISSUE TITLE
403 AccessDenied when using aws-s3 provider

### ISSUE THREAD

**Issue by alifirat** [gaul/s3proxy#522]
Hi, 
I'm using the Docker image (`andrewgaul/s3proxy:sha-ba0fd6d`) to connect S3proxy to S3bucket. Before sharing my issue, let me share my shor-term goal and mid-term goal:
- Short-term => connect S3Proxy to an existing S3 bucket and do read / write on it
- Mid-term => connecto S3proxy to an existing Azure bucket and do read / write on it. 

This is the env variable that I've set: 
```
      - S3PROXY_ENDPOINT=http://0.0.0.0:8080
      - S3PROXY_AUTHORIZATION=aws-v2-or-v4
      - S3PROXY_IDENTITY=local-identity
      - S3PROXY_CREDENTIAL=local-credential
      - S3PROXY_IGNORE_UNKNOWN_HEADERS=true
      - JCLOUDS_PROVIDER=aws-s3
      - JCLOUDS_ENDPOINT=https://mybucket.s3.eu-west-1.amazonaws.com
      - JCLOUDS_IDENTITY=xxx
      - JCLOUDS_CREDENTIAL=xxx
      - JCLOUDS_REGION=eu-west-1
      - LOG_LEVEL=trace
```
Then I'm trying something to use the aws cli 
```
aws --endpoint-url  http://0.0.0.0:8080 s3 cp /tmp/trotro s3://mybucket/                                                                                                                                                            0 [15:53:01]
upload failed: ../../../../../tmp/trotro to s3://mybucket/trotro An error occurred (InvalidAccessKeyId) when calling the PutObject operation: Forbidden ❌ 
// without the proxy AND the same credentials
aws s3 cp /tmp/trotro s3://mybucket/ 
upload: ../../../../../tmp/trotro to s3:/mybucket/trotro ✅ 
```

In the logs, I see 
```
[s3proxy] D 05-11 13:54:39.302 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:299 |::] request: Request(PUT //0.0.0.0:8080/mybucket/trotro)@438913bf
[s3proxy] D 05-11 13:54:39.304 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:324 |::] header: User-Agent: aws-cli/2.11.16 Python/3.11.3 Darwin/22.3.0 source/arm64 prompt/off command/s3.cp
[s3proxy] D 05-11 13:54:39.304 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:324 |::] header: Host: 0.0.0.0:8080
[s3proxy] D 05-11 13:54:39.304 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:324 |::] header: Accept-Encoding: identity
[s3proxy] D 05-11 13:54:39.305 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:324 |::] header: Content-Length: 5
[s3proxy] D 05-11 13:54:39.305 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:324 |::] header: Content-MD5: bM7xsl6lj7i+PKGhp0TqUw==
[s3proxy] D 05-11 13:54:39.306 S3Proxy-Jetty-16 o.gaul.s3proxy.S3ProxyHandler:2945 |::] sendSimpleErrorResponse: 403 InvalidAccessKeyId Forbidden {}
```

can you please help to understand what's wrong here ?

**Comment by alifirat** [comment]
Hey, I'm just coming back that I find the right configuration to make it work. This works for me with the same docker image version. 

```
      - S3PROXY_ENDPOINT=http://0.0.0.0:8080
      - S3PROXY_AUTHORIZATION=none
      - S3PROXY_IDENTITY=local-identity
      - S3PROXY_CREDENTIAL=local-credential
      - S3PROXY_IGNORE_UNKNOWN_HEADERS=true
      - JCLOUDS_PROVIDER=aws-s3
      - JCLOUDS_ENDPOINT=https://s3.eu-west-1.amazonaws.com
      - JCLOUDS_IDENTITY=XXX
      - JCLOUDS_CREDENTIAL=XXX
      - JCLOUDS_REGION=eu-west-1
      - LOG_LEVEL=trace
```

What I have to change was the `JCLOUDS_ENDPOINT` that you can find [here](https://docs.aws.amazon.com/general/latest/gr/s3.html) but I'm still confused by the proxy authentification method. When I set to `aws-v2-or-v4` it's not working anymore, I'm getting 403 Forbidden but my access and secret key are valid.

**Comment by alifirat** [comment]
I was looking to the `AwsSdkTest` and I see that instead of the endpoint, it's the secure endpoint that's used. 
Does it means that when using the auth to `aws-v4` we should use the secure endpoint ?

**Comment by alifirat** [comment]
@gaul if you have any tips to share here 🙏

**Comment by alifirat** [comment]
Closing this because I was able to solve :) 
By the way, s3proxy is compatible with the AWS c++ sdk :-)

**Comment by nkhetia31** [comment]
Hi @alifirat .. were you able to implement it for azure blob storage?  I am getting AccessDenied and Forbidden error for Azure. Thanks.

**Comment by alifirat** [comment]
Hey @nkhetia31 I was able to make it with the Azure backend by following the example in the wiki.
