### ISSUE TITLE
CVE in transitive dependency of com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.13.2

### ISSUE THREAD

**Issue by davewichers** [gaul/s3proxy#527]
org.gaul.s3proxy:2.0.0 - uses com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.13.2, which in turn uses com.fasterxml.woodstox:woodstox-core:6.2.7. Woodstox-core, which has several critical CVEs in it and needs to be upgraded to 6.4.0+.

I looked at your bug/ci-fix branch and see these pom updates are available:

```
++ b/pom.xml
     <dependency>
       <groupId>com.amazonaws</groupId>
       <artifactId>aws-java-sdk-s3</artifactId>
-      <version>1.12.261</version>
+      <version>1.12.481</version>

     <dependency>
       <groupId>javax.xml.bind</groupId>
       <artifactId>jaxb-api</artifactId>
-      <version>2.3.1</version>
+      <version>2.4.0-b180830.0359</version>

     <dependency>
       <groupId>org.junit.jupiter</groupId>
       <artifactId>junit-jupiter</artifactId>
-      <version>5.9.0</version>
+      <version>5.10.0-M1</version>

     <dependency>
       <groupId>com.fasterxml.jackson.dataformat</groupId>
       <artifactId>jackson-dataformat-xml</artifactId>
-      <version>2.13.3</version>
+      <version>2.15.2</version>

     <dependency>
       <groupId>com.github.spotbugs</groupId>
       <artifactId>spotbugs-annotations</artifactId>
-      <version>4.7.1</version>
+      <version>4.7.3</version>

     <dependency>
       <groupId>org.testng</groupId>
       <artifactId>testng</artifactId>
-      <version>7.5</version>
+      <version>7.8.0</version>
```

I ran all the tests and they all still pass so it looks like you can easily upgrade all these.  The important one is jackson-dataformat-xml.  Given that there hasn't been a release in over a year, can you make a release soon (2.1.0) or even a 2.0.1 patch that just upgrades the dependencies to address this?  Thx

**Comment by alifirat** [comment]
See https://github.com/gaul/s3proxy/issues/516#issuecomment-1553959531 for the upcoming release

**Comment by davewichers** [comment]
That doesn't seem to say when the 2.1.0 release is expected to come out. Any ETA for that, along with the above upgrades?

**Comment by davewichers** [comment]
@gaul - Any clue when you are going to do a new release with these dependency upgrades? It's been 6+ weeks.

**Comment by gaul** [comment]
#532.  Please do not spam random issues asking about release.

**Comment by gaul** [comment]
2.1.0 released.
