### ISSUE TITLE
How s3proxy helped us to improve the performance of ClickHouse on Azure

### ISSUE THREAD

**Issue by alifirat** [gaul/s3proxy#530]
Hi, 

Thank you very much for doing s3proxy. 

I was using s3proxy for a project to improve the performance of ClickHouse with a storage on Azure and I would like give back to the community to show how powerful can be s3proxy. 

I don't know what is the right process to add a new reference but at least I can share the blog article here. 

https://engineering.contentsquare.com/2023/clickhouse-on-azure/

**Comment by gaul** [comment]
Thanks for sharing this feedback -- I retweeted from the S3Proxy account!  I will close this issue but please comment if the Azure libraries improve their performance so that S3Proxy is not necessary.  Also open a new issue if you find the Azure compatibility is incomplete.
