### ISSUE TITLE
2.1.0 release

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#532]
This is currently blocked on the Apache jclouds 2.6.0 which I should release in early August.  Further CI is busted on pushing to Docker Hub #479.  Given other open source commitments and upcoming travel I suspect that September is a realistic target.

**Comment by maksym-herbert** [comment]
Hi @gaul, any news about 2.1.0 release date? Thanks!

**Comment by gaul** [comment]
What specifically are you looking to fix in 2.1.0?  Most of the changes are in the jclouds dependency but that release is delayed.  I can run an S3Proxy release more easily but there doesn't seem to be many non-dependency changes:

https://github.com/gaul/s3proxy/compare/s3proxy-2.0.0...master

**Comment by gaul** [comment]
Oh, got it, the Jetty issue.  I can revert the jclouds dependency upgrade to 2.5.0 and release S3Proxy 2.1.0 this weekend.

**Comment by gaul** [comment]
I'm not sure how the Docker CI works these days.  Please let me know if I can do something to push a new image.
