### ISSUE TITLE
9.4.45.v20220203 vulnerability issue

### ISSUE THREAD

**Issue by AkkiSawant** [gaul/s3proxy#533]
S3 proxy has jetty-servlet 9.4.45.v20220203 version which has vulnerabilities. Any idea how to override them in my project pom such that they wont show up.

I tried excluding and specifying a different version still it somehow ends up with the vulnerable version

**Comment by AkkiSawant** [comment]
Looks like the latest code / pom is not updated in maven repo

https://repo.maven.apache.org/maven2/org/gaul/s3proxy/2.0.0/

**Comment by gaul** [comment]
Fixed by #457.  You will need to build from source until I can release 2.1.0 in #532.
