### ISSUE TITLE
azure blob metadata feature request

### ISSUE THREAD

**Issue by TArtiushenko** [gaul/s3proxy#539]
As azure blob does not allow `-` in metadata i propose to replace it with `_` when creating object in azure blob and changing it back to `-` when retrieving object via s3 api

**Comment by gaul** [comment]
As I said in the bug, I don't think this is a good default behavior.  We can add it as an option that is disabled by default or preferably a middleware.  There are various restrictions in all providers and giving users control over this is better than doing something magic for only one.

**Comment by atsai1220** [comment]
Hi @gaul! This seems like a recurring issue. Would you mind sharing some pointers on a new middleware for this application? Thank you!

**Comment by gaul** [comment]
Duplicate of #466.  Please test with the proposed #702.
