### ISSUE TITLE
Improving project

### ISSUE THREAD

**Issue by ryanfaircloth** [gaul/s3proxy#560]
First thank you for all the hard work you've put into this project, I primarily use the project as an overlay for azureblob store but have future considerations for use cases such as swift. I have a fork I am using to merge additional changes both fixes and enhancements I need short term. I've tried to contribute back but with very long PR review time lines and a hectic schedule by the time feedback is given I may have to wait some time myself before I can respond. If you are interested I could share administration over my fork where my focus has been deployment experience improvements for k8s. Perhaps we could share the burden of time required as a technical community around this project

github.com/s3proxy-distro

**Comment by gaul** [comment]
I am happy that you have an interest in improving S3Proxy but disagree that there is any pressing maintenance problem.  There are a few open PRs which are generally incomplete although I can try to prune these to make this more clear.  While I'm sorry that your Helm chart in #428 did not receive much interest from reviewers (I have no idea what this is and Docker CI is busted by another contributor), creating a specific repository for this functionality is a good solution.  As for forking S3Proxy itself, I don't plan to contribute to your fork or give you commit rights to this one.  Maintaining a project might be a greater responsibility than you realize and I encourage you to participate in mainline development, perhaps supporting users in issues and reviewing other's PRs.  You can see my thoughts on this at: http://gaul.org/talks.html#maintaining-sustaining.

**Comment by ryanfaircloth** [comment]
No problem I will just rebase my changes as needed and continue to drop PRs as I have time
