### ISSUE TITLE
Outdated dockerhub image

### ISSUE THREAD

**Issue by RafaMunoz** [gaul/s3proxy#573]
Hello, 

I'm reviewing the image in Docker Hub and I see that the last upload is from 1 year ago and the last Dockerfile generated is from a one weeks ago.

Is it being uploaded to another registry other than dockerhub?

Thank you

**Comment by gaul** [comment]
Unfortunately another contributor broke the automated CI image publishing.  I have pushed an image manually via:

```
mvn clean package -DskipTests
sudo docker build . -t andrewgaul/s3proxy:latest
sudo docker push andrewgaul/s3proxy
```

Please let me know if this works.

**Comment by RafaMunoz** [comment]
Thank you very much, I see the image uploaded.
For future occasions I recommend uploading it also with the version tag since using the latest tag could cause problems in environments that have a specific version.

**Comment by gaul** [comment]
> For future occasions I recommend uploading it also with the version tag since using the latest tag could cause problems in environments that have a specific version.

Pull requests to improve the Docker image are welcome but I won't have time to look into this.
