### ISSUE TITLE
Azure Managed Identity support in S3 proxy

### ISSUE THREAD

**Issue by apoorva-dapake-bh** [gaul/s3proxy#580]
Does s3Proxy support managed identity to connect to azure container?

**Comment by apoorva-dapake-bh** [comment]
There is setting with jcloud 'jclouds.azureblob.auth' to support different Auth methods such as AzureAd and AzureKey.
Is there any setting for managed identity?

**Comment by pegasas** [comment]
here's some introduction about https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/tutorial-linux-vm-access-storage.
looks like it it wait for implementation

**Comment by gaul** [comment]
Duplicate of #536.
