### ISSUE TITLE
java.io.IOException: Too many open files when using Azure Blob backend

### ISSUE THREAD

**Issue by alifirat** [gaul/s3proxy#589]
Hi, 

We are using the following s3proxy configuration (Azure blob backend) with the latest version. 
```
s3proxy.endpoint=http://localhost:8080
# authorization must be aws-v2, aws-v4, aws-v2-or-v4, or none
s3proxy.authorization=aws-v2-or-v4
s3proxy.identity=s3proxyidentity
s3proxy.credential=s3proxycredential
s3proxy.ignore.unknown_headers=true
# 250 * 1024 * 1024 MB
s3proxy.v4-max-non-chunked-request-size=262144000

jclouds.azureblob.auth=azureKey
jclouds.provider=azureblob
jclouds.endpoint=https://XXX.blob.core.windows.net
jclouds.identity=XXX
jclouds.credential=YYY
```

What can lead s3proxy to raise a continuous exception ?
```
java.io.IOException: Too many open files
Jan 05 15:49:40  java[31478]:         at java.base/sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
Jan 05 15:49:40  java[31478]:         at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:533)
Jan 05 15:49:40  java[31478]:         at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:285)
Jan 05 15:49:40  java[31478]:         at org.gaul.shaded.org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:409)
Jan 05 15:49:40  java[31478]:         at org.gaul.shaded.org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:748)
Jan 05 15:49:40  java[31478]:         at org.gaul.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
Jan 05 15:49:40  java[31478]:         at org.gaul.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
Jan 05 15:49:40  java[31478]:         at org.gaul.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
Jan 05 15:49:40  java[31478]:         at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by alifirat** [comment]
For any future readers having the same issue, we just need to increase the max open file and it worked just fine.

**Comment by alifirat** [comment]
For any future readers having the same issue, we just need to increase the max open file and it worked just fine.

**Comment by musabshak** [comment]
> we just need to increase the max open file and it worked just fine.

What was the max open file limit before? What did you change it to?

In the docker image, the max open file descriptors is: 

> ulimit -n 
1,048,576

Was this not enough for your use case? Or, were you running s3Proxy outside of the Docker image such that your fd limit was something less than the 1,048,576 number?

**Comment by gaul** [comment]
I don't think raising the limit is the correct solution.  Somewhere S3Proxy is leaking an InputStream or OutputStream which later gets GCed.  It should be explicitly closed instead.

**Comment by gaul** [comment]
One helpful thing would be for someone to run `lsof` to see if the leaked fds are sockets (probably) or files (unlikely).  There are a few Java tools to debug these kinds of things, e.g., https://github.com/jenkinsci/lib-file-leak-detector

**Comment by Scartiloffista** [comment]
> Was this not enough for your use case?

We bumped, in the same file as OP, the `LimitNOFILE=65536` to `LimitNOFILE=131072`
