### ISSUE TITLE
support 32-bit arm on dockerhub?

### ISSUE THREAD

**Issue by snpz** [gaul/s3proxy#591]
Hi.

I'm using a rather old [Wandboard Quad](https://eu.mouser.com/ProductDetail/Wandboard/WB-IMX6QP-BW?qs=Mv7BduZupUiCXDZfcox9kA%3D%3D) which only has a 32-bit processor.
I would like to run s3proxy via docker, but currently there is only arm64 available, no 32-bit version.

Without docker it works without issues with openjdk 11.
```
# java -version
# openjdk version "11.0.21" 2023-10-17
# OpenJDK Runtime Environment (build 11.0.21+9-post-Debian-1deb11u1)
# OpenJDK Server VM (build 11.0.21+9-post-Debian-1deb11u1, mixed mode)
```

I found #382 and it made its way into dockerhub too. Would it be possible to also provide this for my kind of outdated cpu-architecture?
```
# uname -a
# Linux wandboard 5.10.0-26-armmp #1 SMP Debian 5.10.197-1 (2023-09-29) armv7l GNU/Linux
```

I'd totally understand if not. :)

**Comment by gaul** [comment]
Currently the automated Docker push via CI is broken #479.  Before a contributor added ARM64 support, this worked for x86-64.  Ideally I would like to repair this if someone can tell me what is broken.  Then I would be happy to accept a PR to include 32-bit ARM as part of the automated push.  I don't have much background in Docker so this will likely need to be a contribution from the community.
