### ISSUE TITLE
S3Proxy not compatible with some AWS java sdk v2

### ISSUE THREAD

**Issue by ssyssy** [gaul/s3proxy#704]
I write my JAVA integration with the S3ProxyRule set.
When I try to use the AsyncS3client.getObject API calls,
I hit the 

A header you provided implies functionality that is not implemented.

Exception. Anyone know about this?

**Comment by gaul** [comment]
Can you run S3Proxy with `java -DLOG_LEVEL=trace` so we can find which header causes problems?

**Comment by jerbob92** [comment]
We saw that this has already been fixed but that the `latest` docker tag is really outdated (over a year old), probably that does not get updated correctly anymore.

Also: any chance you could tag the docker images with the version from the GitHub release as well?

**Comment by gaul** [comment]
Unfortunately I don't understand how the Docker images are being generated currently.  I see new tags pushed but not updating the latest tag as I would expect nor version tags.  Could you or a previous contributor like @snpz fix this automation?  I can push a manual tag otherwise but I would prefer to focus on the backlog of S3 compatibility bugs.

**Comment by jerbob92** [comment]
@gaul look into the CI config for a bit and should be pretty simple to fix!

CI is not ran on tags, so it also doesn't make the docker container for tags:
https://github.com/gaul/s3proxy/blob/master/.github/workflows/ci-main.yml#L3

If you change it to:

```
on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
```

It should work.

`flavor` latest is set to `false`, so it never makes the latest tag:
https://github.com/gaul/s3proxy/blob/master/.github/workflows/ci-main.yml#L37

I think if you just set this to `auto`, it will work. It should automatically update latest when a new tag is made.

**Comment by gaul** [comment]
Pushed -- let's let CI run and see if this fixes the issue.

**Comment by jerbob92** [comment]
@gaul nice! It does require to push a tag to make it "work"
