### ISSUE TITLE
Just a reminder to build/push the new docker image to andrewgaul/s3proxy

### ISSUE THREAD

**Issue by Jayd603** [gaul/s3proxy#725]
I would do it for you if I could.  : - )

Thanks for this work btw, I created an s3 proxy gateway that uses these docker images, currently, each user/bucket gets their own docker image spawned in order to handle multiple users.  The same backend is used that contains files for all these users/buckets but each s3proxy sets the correct directory.   It's sort of a hack way to do multiple users on the same backend since a lot of users means much larger memory wasted rather than building it into s3proxy directly but it's fine for now for me.

**Comment by gaul** [comment]
Could you be more precise about which Docker images you want pushed?  On https://hub.docker.com/r/andrewgaul/s3proxy/tags I see an updated master, every commit pushed, and a handful of older release tags.  I'm not sure why 1.9.0 is the latest release tag though.  Is this what you are referring to?

Could you open a separate issue describing your multi-tenant use case?  There is no inherent reason that S3Proxy cannot support multiple users and this is mostly a configuration and mapping issue.

**Comment by Jayd603** [comment]
Oh my bad, i'm lazy and didn't look.   Yah i did a docker pull for latest and the latest tag isn't on the new one, that's what it is.

**Comment by gaul** [comment]
@snpz Is this working as intended or do I need to do something else for releases and the latest tag?

**Comment by Jayd603** [comment]
Well, should the latest tag be on the latest release?  right now it's pretty old.

**Comment by gaul** [comment]
Sorry I forgot about our discussion in #704.  Let me run a new release and see what happens.

**Comment by gaul** [comment]
I believe this is fixed: https://hub.docker.com/r/andrewgaul/s3proxy/tags
