### ISSUE TITLE
Separator in Window

### ISSUE THREAD

**Issue by ccarlenzoli** [gaul/s3proxy#740]
I'm using the tool in Openshift working perfectly but when I tried to test on my Notebook some features of my application I ended up with an error on managing Folders.
Since I'm working on Windows I understood that problem is related to a wrong management of file separator. 
I did a workaround at line 1518 of S3ProxyHanlder changing this code

 switch (metadata.getType()) {
                case FOLDER:
                    // fallthrough
                case RELATIVE_PATH:
                    if (delimiter != null) {
                        commonPrefixes.add(metadata.getName());
                        continue;
                    }
                    break;
                default:
                    break;
                }

in

 switch (metadata.getType()) {
                case FOLDER:
                    // fallthrough
                case RELATIVE_PATH:
                    if (delimiter != null) {
                       commonPrefixes.add(metadata.getName().replace(File.separatorChar, '/'));
                        continue;
                    }
                    break;
                default:
                    break;
                }

following the same code LocalBlobStore (jclouds) is doing in its filterDirectory method.

Hope you will officially fix this behavior so I will use the new version from Maven Repo...otherwise I have to keep a local copy :) 

Best

**Comment by gaul** [comment]
This sounds like a problem in the underlying jclouds filesystem provider.  I don't have access to a Windows system so this is hard for me to test.  Instead could you try the new filesystem-nio2 storage backed to see if it already resolves your symptoms?

**Comment by gaul** [comment]
Please test filesystem-nio2 with the latest master or 2.5.0-SNAPSHOT from Maven.  If you would like to contribute a fix to jclouds filesystem this is fine but it is better to focus on the newer filesystem-nio2 storage backend which will replace the former.
