### ISSUE TITLE
support bucket-in-hostname

### ISSUE THREAD

**Issue by gaul** [gaul/s3proxy#8]
S3Proxy supports bucket-in-path URLs, e.g., example.com/bucket-name/blob-name.  It should also support bucket-in-hostname URLs, e.g., bucket-name.example.com/blob-name.

**Comment by andrewgaul** [comment]
s3cmd 1.5.0 supports bucket-in-path, see s3tools/s3cmd#375 and s3tools/s3cmd#416.
